ONB 204 responsive design
mobileaction-juniors/demo-frontend-example pull request #50
Opened 2024-07-16 06:50 UTC by eececan

The design is now responsive
UI & UX is improved

2024-07-17 07:21 UTC, tinas requested changes

2024-07-17 07:21 UTC, tinas commented on src/stores/textStore.js
> +export const textStore = defineStore('texts', () => {
We have to be careful with store naming. In the Pinia documentation you can read an explanation of why they are named this way: https://pinia.vuejs.org/core-concepts/#Defining-a-Store

```suggestion
export const useTextStore = defineStore('texts', () => {
```

2024-07-17 07:21 UTC, tinas commented on src/pages/keyword-generator/KeywordGenerator.vue
> +  width: 150px !important;
we should not use `!important` unless we really need it. You can read more in this article: https://element.how/why-you-should-avoid-using-important-in-css/

2024-07-17 07:21 UTC, tinas commented on src/pages/keyword-generator/KeywordGenerator.vue
> +<style>
```suggestion
<style scoped>
```

2024-07-17 07:21 UTC, tinas commented on src/main.js
> +
```suggestion
```

2024-07-17 07:21 UTC, tinas commented on src/main.js
> +
We should delete unnecessary/empty lines.

2024-07-17 07:21 UTC, tinas commented on src/pages/keyword-density/KeywordDensity.vue
> +const store = textStore()
```suggestion
const textStore = useTextStore()
```

2024-07-17 07:21 UTC, tinas commented on src/pages/keyword-density/KeywordDensity.vue
> +const text = storeToRefs((store)).userInputText;
We don't need this variable.

2024-07-17 07:21 UTC, tinas commented on src/pages/keyword-density/KeywordDensity.vue
>                v-model:value="text"
```suggestion
              v-model:value="textStore.userInputText"
```

2024-07-17 07:21 UTC, tinas commented on src/pages/keyword-density/KeywordDensity.vue
> +const totalCharacters = ref(text.value.length);
`totalCharacter` should be computed property.

```suggestion
const totalCharacters = computed(() => textStore.userInputText.length);
```

2024-07-17 11:28 UTC, tinas commented on src/pages/keyword-density/KeywordDensity.vue
> +const text = storeToRefs((store)).userInputText;
Instead of `text.value` we can use `store.userInputText` directly.

2024-07-17 11:35 UTC, eececan commented on src/pages/keyword-density/KeywordDensity.vue
> +    "efficitur libero maximus quis.";
I used this method for readibility, not for a multiline string.

2024-07-18 06:06 UTC, eececan commented on src/pages/index.vue
> +import router from "@/router/index.js";
In index.js file, i have imported from vue-router:

import { createRouter, createWebHistory } from 'vue-router'

2024-07-19 12:49 UTC, tinas approved these changes

2024-07-19 12:49 UTC, tinas commented on src/pages/keyword-density/KeywordDensity.vue
>  import router from "@/router/index.js";
```suggestion
import { useRouter } from 'vue-router';
```

Example
```js
const router = useRouter();

router.push('/keyword-generator');
```

2024-07-22 09:00 UTC, merged